modLoader="javafml" #mandatory
loaderVersion="[34,)"
license="GNU LESSER GENERAL PUBLIC LICENSE Version 2.1"

[[mods]]
modId="reputation"
version="0.6.2"
displayName="Reputation"
displayURL=""
updateJSONURL=""
credits=""
authors="The_Computerizer"
description=""

