modLoader="javafml" #mandatory
loaderVersion="[34,)"
license="MIT"

[[mods]]
modId="reputation"
version="0.9.5"
displayName="Reputation"
displayURL=""
updateJSONURL=""
credits=""
authors="The_Computerizer"
description=""

